x-ignition-common: &ignition-common
  image: inductiveautomation/ignition:8.3.2
  user: 0:0

services:
  ignition-gateway:
    <<: *ignition-common
    ports:
      - 8088:8088
      - 8043:8043
    volumes:
      - ./gw-projects/ignition-rag:/usr/local/bin/ignition/data/projects/ignition-rag
      - ./gw-config/ignition-rag/:/usr/local/bin/ignition/data/config/
      - ./pdfbox-app-3.0.6.jar:/usr/local/bin/ignition/lib/core/gateway/pdfbox-app-3.0.6.jar
    environment:
      # - GATEWAY_ADMIN_USERNAME=admin
      # - GATEWAY_ADMIN_PASSWORD=password
      # - ACCEPT_IGNITION_EULA=Y
      - IGNITION_EDITION=standard
      - DISABLE_QUICKSTART=true
      - IGNITION_UID=2003
      - IGNITION_GID=2003
        
    command: >
      -n ignition-gateway
      --
      wrapper.java.initmemory=4096
      -Dignition.projects.scanFrequency=10
      -Dignition.allowunsignedmodules=true

  postgres:
    image: pgvector/pgvector:pg18
    container_name: postgres-pgvector
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ragdb
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_USE_MMAP=true
    # Uncomment below to run on GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: ${OLLAMA_GPU_DRIVER-nvidia}
    #           count: ${OLLAMA_GPU_COUNT-1}
    #           capabilities:
    #             - gpu

volumes:
  postgres-data:
  ollama_data: